### ISSUE TITLE
Add support for custom scalar types

### ISSUE THREAD

**Issue by kramsey458** [autoinvent/magql#16]
Custom scalar types need to be implemented in order to allow input validation for MagqlInputFields.
According to: https://github.com/MichalLytek/type-graphql/blob/master/docs/validation.md, this is the best way to ensure that inputs are arguments are correct.

This is also necessary for #13 since pagination input only allows positive numbers.

**Comment by Tworley96** [comment]
Adding an issue description from a previous revision of this issue: 

Graphql Core Next Scalar implementation page: https://github.com/graphql-python/graphql-core-next/blob/master/src/graphql/type/scalars.py
Graphql's extremely indepth documentation on how to add a custom scalar: https://graphql.org/learn/schema/#scalar-types
Slightly better instruction on how you would go about adding a custom scalar from Apollo: https://www.apollographql.com/docs/graphql-tools/scalars/
Rough guidance: Create a MagqlScalarType class that mirrors the GraphQLScalarType class in the parameters that it's init accepts. No need to update the existing builtin scalars to use this. Pass the newly created MagqlScalarTypes to convert so that it can use them.
