### ISSUE TITLE
get_magql_filter_type argument names are confusing

### ISSUE THREAD

**Issue by davidism** [autoinvent/magql#45]
`get_magql_filter_type(type_, base_type)` doesn't match `_get_magql_filter_type(column, base_type)`. It appears the public one is being called with a SQLA column and a Magql type, while the private one is actually passing a `type` to the `column` argument. This also doesn't match the arguments of `get_magql_type`, which passes on the `column` to the functions.

**Comment by Tworley96** [comment]
`_get_magql_filter_type(column, base_type`)` can be renamed to `get_magql_filter_type` and the current existing `get_magql_filter_type` can be removed. This will fix the naming issues. The arguments of `get_magql_filter_type` and `get_magql_type` are different because some of their dispatched functions require different values. Not sure what can be done with that. Its possible there is a better approach to this for single_dispatch.
