### ISSUE TITLE
Reference implementation

### ISSUE THREAD

**Issue by olirice** [autoinvent/magql#62]
Hey 👋

I maintain a similar python project [nebulo](https://github.com/olirice/nebulo) ([docs](https://olirice.github.io/nebulo/)) that reflects a GraphQL API from sqlalchemy models or directly from a postgres database. Its effectively a minimal (reads: worse) python clone of [PostGraphile](https://www.graphile.org/postgraphile/).

I mostly just wanted to say hi and provide a link to the project in case it can be useful as a reference/comparison/whatever 

Some entrypoints that might be interesting are:

[The sqla model to GQL schema translation](https://github.com/olirice/nebulo/blob/master/src/nebulo/gql/sqla_to_gql.py#L25)
and
[query builder](https://github.com/olirice/nebulo/blob/master/src/nebulo/gql/resolve/transpile/query_builder.py)

Are you targeting support for every database that sqlalchemy supports, or just the big ones like postgres, mysql, sqlite, and mssql?

**Comment by davidism** [comment]
Hello! Cool to see others working in this space. I'm currently refactoring and documenting this library, so don't look too hard yet :see_no_evil:

We did some work with our query builder to generate one query with the appropriate joins instead of causing queries for each relationship traversal. I'm fairly sure we always generate one query, but I'm not sure, I'll take a look at yours too.

We're targeting general support for SQLAlchemy, we don't use any database-specific code in our own projects, so we don't really have a reference for what that support would look like. We're actually in the process of extracting the SQLAlchemy converter from Magql core, so that other extensions could generate Magql schema from other data models.

**Comment by davidism** [comment]
We just released Magql 1.0. This represents a complete rewrite since you commented here, and should be much more straightforward to use, including better documentation and tests. You can check out the documentation for the three libraries here:

- [Magql](https://magql.autoinvent.dev), the core library (this repo)
- [Magql-SQLAlchemy](https://magql-sqlalchemy.autoinvent.dev), generates a Magql schema from SQLAlchemy models
- [Flask-Magql](https://flask-magql.autoinvent.dev), hosts a Magql schema with Flask
